// Project scaffolding: tsgo output → sci/sa project layout.
//
// A generated project is a directory:
//
//	<out>/
//	  sa.mod          package manifest (sci grammar: package "<name>")
//	  src/main.ts     gated subset-TS (the middle "ts" artifact, canonical)
//	  src/main.sai    generated SA-ASM (sci `sa build` input)
//	  subset-report.txt  refusals/warnings with locations (the "ts" gate log)
//	  README.md
//	  build.sh        invokes `sa build-exe src/main.sai -o main[.exe]`
//
// The .sai carries its own `@import "sa_std/..."` header lines (emitted by
// the lowerer per used projection-table entry); imports resolve against the
// sci compiler-shipped sa_std at build time, so the scaffold vendors nothing.
package saemit

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ScaffoldOptions controls project generation.
type ScaffoldOptions struct {
	// ModuleName is the sa.mod package name, e.g. "hello_sa".
	ModuleName string
	// Sources maps a logical name (e.g. "main") to TS source text.
	Sources map[string]string
	// FileName is used in diagnostics for the single-source case.
	FileName string
}

// Scaffold lowers each source and writes the sci/sa project into outDir.
// It returns per-source results; if any source refused, the project is still
// written (with subset-report.txt explaining the gate), but the caller must
// NOT assemble the partial .sai files.
func Scaffold(outDir string, opts ScaffoldOptions) (map[string]Result, error) {
	if opts.ModuleName == "" {
		opts.ModuleName = "tsgo_sa_app"
	}
	if err := os.MkdirAll(filepath.Join(outDir, "src"), 0o755); err != nil {
		return nil, err
	}
	results := map[string]Result{}
	names := []string{}
	for name := range opts.Sources {
		names = append(names, name)
	}
	// Deterministic order for stable output.
	for i := 0; i < len(names); i++ {
		for j := i + 1; j < len(names); j++ {
			if names[j] < names[i] {
				names[i], names[j] = names[j], names[i]
			}
		}
	}
	report := strings.Builder{}
	for _, name := range names {
		src := opts.Sources[name]
		file := opts.FileName
		if file == "" {
			file = name + ".ts"
		}
		res := Lower(file, src)
		results[name] = res
		if err := os.WriteFile(filepath.Join(outDir, "src", name+".ts"), []byte(res.SubsetTS), 0o644); err != nil {
			return nil, err
		}
		if err := os.WriteFile(filepath.Join(outDir, "src", name+".sai"), []byte(res.SAI), 0o644); err != nil {
			return nil, err
		}
		fmt.Fprintf(&report, "== %s.ts: %d diagnostic(s), refused=%v ==\n", name, len(res.Diagnostics), res.Refused)
		for _, d := range res.Diagnostics {
			fmt.Fprintf(&report, "%s\n", d.Error())
		}
	}
	if err := os.WriteFile(filepath.Join(outDir, "subset-report.txt"), []byte(report.String()), 0o644); err != nil {
		return nil, err
	}
	mainSai := "src/main.sai"
	if _, ok := opts.Sources["main"]; !ok && len(names) > 0 {
		mainSai = "src/" + names[0] + ".sai"
	}
	files := map[string]string{
		"sa.mod":    fmt.Sprintf("package \"%s\"\n", opts.ModuleName),
		"README.md": readmeText(opts.ModuleName, mainSai),
		"build.sh":  buildScriptText(mainSai),
	}
	for rel, content := range files {
		if err := os.WriteFile(filepath.Join(outDir, rel), []byte(content), 0o644); err != nil {
			return nil, err
		}
	}
	return results, nil
}

func readmeText(mod, mainSai string) string {
	var b strings.Builder
	b.WriteString("# " + mod + " (tsgo -> SA)\n\n")
	b.WriteString("Generated by tsgo-sa: TypeScript lowered to SA-ASM for the sci/sa toolchain\n")
	b.WriteString("(pipeline tsgo -> ts -> sa).\n\n")
	b.WriteString("## Layout\n\n")
	b.WriteString("- sa.mod: package manifest\n")
	b.WriteString("- src/*.ts: gated subset-TS (canonical source; see subset-report.txt)\n")
	b.WriteString("- src/*.sai: generated SA-ASM (sa build input)\n")
	b.WriteString("- subset-report.txt: subset-gate log; refusals must be resolved before assembling\n\n")
	b.WriteString("All TS standard library calls project onto compiler-shipped sci/sa_std\n")
	b.WriteString("(@import \"sa_std/...\" in the .sai header); nothing is vendored and the\n")
	b.WriteString("frontend simulates no runtime behavior.\n\n")
	b.WriteString("## Build\n\n")
	b.WriteString("    sh build.sh\n\n")
	b.WriteString("Entry: " + mainSai + "\n")
	return b.String()
}

func buildScriptText(mainSai string) string {
	return fmt.Sprintf(`#!/usr/bin/env sh
# Build the generated SA project with the sci toolchain.
# Requires the sci 'sa' binary on PATH (sci/zig-out/bin/sa).
set -eu
SA_BIN="${SA_BIN:-sa}"
"$SA_BIN" build-exe %s -o main
`, mainSai)
}
